# Generated by Django 5.2.4 on 2025-10-23 09:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakePlayerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_fake_players', models.PositiveIntegerField(default=50)),
                ('calls_before_fake_winner', models.PositiveIntegerField(default=10)),
                ('real_players_threshold', models.PositiveIntegerField(default=10)),
                ('fake_players_can_win', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fake Player Settings',
                'verbose_name_plural': 'Fake Player Settings',
            },
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_countdown_duration', models.PositiveIntegerField(default=30)),
                ('default_game_speed', models.PositiveIntegerField(default=5000)),
                ('default_house_edge', models.DecimalField(decimal_places=2, default=22.0, max_digits=5)),
                ('max_fake_players', models.PositiveIntegerField(default=50)),
                ('fake_player_threshold', models.PositiveIntegerField(default=10)),
                ('fake_players_can_win', models.BooleanField(default=True)),
                ('fake_winner_probability', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('max_games_per_day', models.PositiveIntegerField(default=1000)),
                ('max_games_per_hour', models.PositiveIntegerField(default=100)),
                ('min_entry_fee', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_entry_fee', models.DecimalField(decimal_places=2, default=10000.0, max_digits=10)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game Settings',
                'verbose_name_plural': 'Game Settings',
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP'), ('tournament', 'Tournament')], default='standard', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('max_players', models.PositiveIntegerField(default=100)),
                ('min_players', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('countdown_duration', models.PositiveIntegerField(default=30)),
                ('game_speed', models.PositiveIntegerField(default=5000)),
                ('max_fake_players', models.PositiveIntegerField(default=50)),
                ('fake_player_threshold', models.PositiveIntegerField(default=10)),
                ('house_edge_percentage', models.DecimalField(decimal_places=2, default=22.0, max_digits=5)),
                ('prize_pool_percentage', models.DecimalField(decimal_places=2, default=78.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Room',
                'verbose_name_plural': 'Game Rooms',
                'ordering': ['entry_fee', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('countdown', 'Countdown'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='waiting', max_length=20)),
                ('total_players', models.PositiveIntegerField(default=0)),
                ('real_players', models.PositiveIntegerField(default=0)),
                ('fake_players', models.PositiveIntegerField(default=0)),
                ('total_entry_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('house_edge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('winner_is_fake', models.BooleanField(default=False)),
                ('winner_card_number', models.PositiveIntegerField(blank=True, null=True)),
                ('countdown_started_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('numbers_called', models.PositiveIntegerField(default=0)),
                ('total_numbers_called', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='game.gameroom')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_number', models.PositiveIntegerField()),
                ('card_data', models.JSONField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numbers_matched', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_player_games', to='finance.transaction')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to=settings.AUTH_USER_MODEL)),
                ('win_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='win_player_games', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Player Game',
                'verbose_name_plural': 'Player Games',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['entry_fee'], name='game_gamero_entry_f_ee3635_idx'),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['room_type'], name='game_gamero_room_ty_138f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['room', 'created_at'], name='game_game_room_id_11bd05_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['winner', 'created_at'], name='game_game_winner__4681ce_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'),
        ),
        migrations.AddIndex(
            model_name='playergame',
            index=models.Index(fields=['game', 'is_winner'], name='game_player_game_id_d08d35_idx'),
        ),
        migrations.AddIndex(
            model_name='playergame',
            index=models.Index(fields=['user', 'is_winner'], name='game_player_user_id_ff7584_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playergame',
            unique_together={('game', 'user')},
        ),
    ]
