# Generated by Django 5.2.4 on 2025-10-23 09:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('countdown', 'Countdown'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='waiting', max_length=20)),
                ('total_players', models.PositiveIntegerField(default=0)),
                ('real_players', models.PositiveIntegerField(default=0)),
                ('fake_players', models.PositiveIntegerField(default=0)),
                ('total_entry_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('house_edge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('winner_is_fake', models.BooleanField(default=False)),
                ('winner_card_number', models.PositiveIntegerField(blank=True, null=True)),
                ('countdown_started_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('numbers_called', models.PositiveIntegerField(default=0)),
                ('total_numbers_called', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_number', models.PositiveIntegerField()),
                ('card_data', models.JSONField()),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numbers_matched', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Game',
                'verbose_name_plural': 'Player Games',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['winner', 'created_at'], name='game_game_winner__4681ce_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='game_game_status_9bfe99_idx'),
        ),
        migrations.AddIndex(
            model_name='playergame',
            index=models.Index(fields=['game', 'is_winner'], name='game_player_game_id_d08d35_idx'),
        ),
        migrations.AddIndex(
            model_name='playergame',
            index=models.Index(fields=['user', 'is_winner'], name='game_player_user_id_ff7584_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playergame',
            unique_together={('game', 'user')},
        ),
    ]
