# Generated by Django 5.2.4 on 2025-07-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergame',
            name='card',
        ),
    ]
