# Generated by Django 5.2.4 on 2025-07-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_playergame_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_speed', models.IntegerField()),
                ('count_down_time', models.IntegerField()),
            ],
        ),
    ]
