# Generated by Django 5.2.4 on 2025-07-29 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='game_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='game_start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='number_of_players',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='winner_name',
            field=models.CharField(default='adaa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='winner_telegram_id',
            field=models.CharField(default=32423432, max_length=255),
            preserve_default=False,
        ),
    ]
