
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bingo_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/bingo_db"
      JWT_SECRET: lsdafndkf983qy481asdkbfaksdbjf
      JWT_REFRESH_SECRET: lsdafndkf983qy481asdkbfaksdbjf
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bingo-network

    

  app:
    dns:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    build: ./app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bingo_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVER_URL: https://server.akerbingo.com/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bingo-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: bingo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bingo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bingo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  bingo-network:
    driver: bridge
