# Generated by Django 5.2.4 on 2025-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='e8zgZ3DuVQFlLUP', max_length=15),
        ),
    ]
