# Generated by Django 5.2.4 on 2025-07-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='5lDKWvrxlUkwRnV', max_length=15),
        ),
    ]
