# Generated by Django 5.2.4 on 2025-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='Sus0OimkC1HVEn0', max_length=15),
        ),
    ]
