# Generated by Django 5.2.4 on 2025-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='F9yrJ8piHqOotJk', max_length=15),
        ),
    ]
