# Generated by Django 5.2.4 on 2025-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='tBbnzhiFmJGgYmo', max_length=15),
        ),
    ]
