# Generated by Django 5.2.4 on 2025-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='M4MLkAw938Exqp0', max_length=15),
        ),
    ]
