# Generated by Django 5.2.4 on 2025-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='CoUwJAb0D6i4BDE', max_length=15),
        ),
    ]
