# Generated by Django 5.2.4 on 2025-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='nDjq7a7ESF9d0Nw', max_length=15),
        ),
    ]
