# Generated by Django 5.2.4 on 2025-09-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='mTms3ZqEgOG4v9V', max_length=15),
        ),
    ]
