# Generated by Django 5.2.4 on 2025-07-17 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_chapasession'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapasession',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
