# Generated by Django 5.2.4 on 2025-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_chapasession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapasession',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
