# Generated by Django 5.2.4 on 2025-07-18 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_chapasession_ref_id_alter_chapasession_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapasession',
            old_name='tx_ref',
            new_name='trx_ref',
        ),
    ]
