# Generated by Django 5.2.4 on 2025-07-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_rename_tx_ref_chapasession_trx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapasession',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
