# Generated by Django 5.2.4 on 2025-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_transaction_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapasession',
            old_name='trx_ref',
            new_name='tx_ref',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw')], max_length=20),
        ),
    ]
