# Generated by Django 5.2.4 on 2025-09-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_addispaysession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addispaysession',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='addispaysession',
            name='return_url',
        ),
    ]
