# Generated by Django 5.2.4 on 2025-09-04 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('awareness', 'Brand Awareness'), ('acquisition', 'User Acquisition'), ('retention', 'Player Retention'), ('monetization', 'Monetization')], max_length=20)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('advertiser_name', models.CharField(max_length=100)),
                ('advertiser_email', models.EmailField(max_length=254)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner'), ('popup', 'Popup'), ('interstitial', 'Interstitial'), ('video', 'Video'), ('native', 'Native'), ('sponsored', 'Sponsored Content')], default='banner', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('click_url', models.URLField()),
                ('target_game_types', models.JSONField(default=list, help_text='List of game types to target')),
                ('min_player_level', models.IntegerField(default=1)),
                ('max_player_level', models.IntegerField(default=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_click', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('cost_per_impression', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('daily_budget_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_countries', models.JSONField(default=list, help_text='List of country codes')),
                ('target_languages', models.JSONField(default=list, help_text='List of language codes')),
                ('target_age_min', models.IntegerField(default=18)),
                ('target_age_max', models.IntegerField(default=99)),
                ('max_impressions_per_user', models.IntegerField(default=3)),
                ('display_frequency_hours', models.IntegerField(default=24, help_text='Hours between showing same ad to user')),
                ('priority', models.IntegerField(default=1, help_text='Higher number = higher priority')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('total_impressions', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='marketing.adcampaign')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_country', models.CharField(blank=True, max_length=2)),
                ('user_language', models.CharField(blank=True, max_length=5)),
                ('game_type', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='marketing.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('impression', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='click', to='marketing.adimpression')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='marketing.advertisement')),
            ],
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='marketing_a_status_97508f_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['target_game_types'], name='marketing_a_target__f4d6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['priority'], name='marketing_a_priorit_fc5db2_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['advertisement', 'user_id', 'created_at'], name='marketing_a_adverti_6e71e5_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['user_id', 'created_at'], name='marketing_a_user_id_a79aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='adimpression',
            index=models.Index(fields=['created_at'], name='marketing_a_created_bfb927_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['advertisement', 'created_at'], name='marketing_a_adverti_d74ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['user_id', 'created_at'], name='marketing_a_user_id_959164_idx'),
        ),
    ]
